version: '3'
services:
  sandbox:
    build:
      context: .
    volumes:
      - .:/code
    command: tail -f /dev/null
    # TODO: load this from an environment variable so M1 macs can easily use this
    platform: linux/x86_64
